### ISSUE TITLE
Premature confetti fade out

### ISSUE THREAD

**Issue by alexbirkett** [DanielMartinus/Konfetti#205] opened 2020-10-08 13:32 UTC
On slower devices, the confetti fades out higher up the screen than on faster devices:

| Nokia 1 | OnePlus 8 |
|-|-|
| <img src="https://user-images.githubusercontent.com/530659/95453603-70969700-096b-11eb-8cbc-8da5be7e301f.png" width=300/> | <img src="https://user-images.githubusercontent.com/530659/95465325-48af2f80-097b-11eb-9a6f-cbf0369661c9.png" width=300/> |

**Comment by alexbirkett** [comment] 2020-10-08 13:36
Maybe the fade should be a function of the particle's Y value not time?

**Comment by DanielMartinus** [comment] 2020-10-08 18:44
Interesting! Thanks for reporting @alexbirkett. Question, could it be that this OnePlus 8 has a 120hz display? I think it has to do with the refresh time not being calculated down to the fade.

**Comment by alexbirkett** [comment] 2020-10-09 06:20
But the behaviour is as expected on the OnePlus. It's the slow phones (like the Nokia and emulators according to my college) that have problems. I added support for text/emojis and the problem was even more apparent then.

**Comment by carlfindahl** [comment] 2020-10-09 09:06
Do you use a delta time multiplier when altering the particle attributes? If not, that might help.

**Comment by DanielMartinus** [comment] 2020-10-10 11:50
> Do you use a delta time multiplier when altering the particle attributes? If not, that might help.

Yes, it's used and it seems to be used for the alpha too. I'm trying to think of a way to validate it's because of the frame rate by perhaps limiting the fps.

**Comment by DanielMartinus** [comment] 2020-10-25 19:50
Did a quick test and forced Konfetti to draw on a with lower frames per seconds and it indeed visibly makes the particles have a shorter lifespan (see comparison below). Since I'm not able to reproduce it I'll have to dig deeper to find out why this is happening.

| ~30fps | ~60fps |
|-|-|
| ![Screenshot_1603655172](https://user-images.githubusercontent.com/1636897/97117350-64e4f780-1703-11eb-8861-10ddd0b09bdf.png) | ![Screenshot_1603655212](https://user-images.githubusercontent.com/1636897/97117352-67475180-1703-11eb-8316-b1f5fee1bdab.png) |

**Comment by DanielMartinus** [comment] 2020-10-25 21:08
Hey @alexbirkett,

The deltatime wasn't calculated on the force and acceleration. Hence it didn't reach as far on the slower phone as it did on the faster phone. Could you try and test the following version on the slower phone to see if it's fixed?

```
implementation 'nl.dionsegijn:konfetti:1.2.6-rc1' 
```

**Comment by alexbirkett** [comment] 2020-10-27 13:57
I can't find a tag for `1.2.6-rc1`. When I attempt to use `'nl.dionsegijn:konfetti:1.2.6-rc1' ` with `demo-simple-java` I get a crash:

```
    Process: nl.dionsegijn.simple_demo, PID: 28955
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at nl.dionsegijn.konfetti.models.Shape$DrawableShape.<init>(Unknown Source:2)
        at nl.dionsegijn.simple_demo.MainActivity.onCreate(MainActivity.java:23)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7386)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/nl.dionsegijn.simple_demo-a0luL6QpGPUoNEidnRfcag==/base.apk"],nativeLibraryDirectories=[/data/app/nl.dionsegijn.simple_demo-a0luL6QpGPUoNEidnRfcag==/lib/arm, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at nl.dionsegijn.konfetti.models.Shape$DrawableShape.<init>(Unknown Source:2) 
        at nl.dionsegijn.simple_demo.MainActivity.onCreate(MainActivity.java:23) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7386) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
```

**Comment by DanielMartinus** [comment] 2020-10-28 11:28
@alexbirkett that's because kotlin isn't configured for this java project. 

You can easily fix that by adding a dummy kotlin class file to that `demo-simple-java` project and then click on configure kotlin

<img src="https://user-images.githubusercontent.com/1636897/97430358-1446e780-1919-11eb-9111-62b77e73538a.png" width=300/>

**Comment by DanielMartinus** [comment] 2020-11-25 09:31
@alexbirkett would it be possible to try above solution?

**Comment by DanielMartinus** [comment] 2021-03-14 15:22
Presumably fixed with this implementation:  https://github.com/DanielMartinus/Konfetti/pull/249

Please reopen if the problem still occurs

**Closed by DanielMartinus** 2021-03-14 15:22 UTC
Labels: bug
