### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by eawedat** [DanielMartinus/Konfetti#75] opened 2019-03-09 16:14 UTC
I'm trying to implement Konfetti library using java code, but I get this error:
It seems something related to Kotlin while I'm using Java,

2019-03-09 18:10:46.023 14058-14058/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.particle3, PID: 14058
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at nl.dionsegijn.konfetti.KonfettiView.onDraw(Unknown Source:2)
        at android.view.View.draw(View.java:19226)
        at android.view.View.updateDisplayListIfDirty(View.java:18176)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at com.android.internal.policy.DecorView.draw(DecorView.java:791)
        at android.view.View.updateDisplayListIfDirty(View.java:18176)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3051)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2846)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2399)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1432)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6861)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
2019-03-09 18:10:46.026 14058-14058/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/base.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 48 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:695)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:729)
        at android.app.LoadedApk.getResources(LoadedApk.java:956)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        		... 5 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.particle3-PoJzt4mGNj3x2DeFOgkRwg==/split_lib_slice_5_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
2019-03-09 18:10:46.027 14058-14058/? E/AndroidRuntime:     at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:695)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:729)
        at android.app.LoadedApk.getResources(LoadedApk.java:956)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        		... 5 more

**Comment by Ethan1983** [comment] 2019-03-09 16:33
I think, it was documented. Try this,

implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21'

**Comment by eawedat** [comment] 2019-03-09 16:35
Ehtan1983, thank you for replying, 
I don't understand, why do I need to implement Kotlin while I'm not using it?

**Comment by Ethan1983** [comment] 2019-03-09 17:16
https://github.com/DanielMartinus/Konfetti/issues/47

https://medium.com/@preslavrachev/kotlin-basics-create-executable-kotlin-jars-using-gradle-d17e9a8384b9

**Comment by DanielMartinus** [comment] 2019-03-10 11:41
What @Ethan1983 says indeed, in order use this kotlin library you also need the underlying Kotlin standard library. Closing this issue now since it's a duplicate of #47.

**Closed by DanielMartinus** 2019-03-10 11:41 UTC
